[package]
name = "omarchy-whatsappd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
aes.workspace = true
anyhow.workspace = true
async-trait.workspace = true
buffa.workspace = true
cbc.workspace = true
chrono.workspace = true
clap.workspace = true
futures.workspace = true
hkdf.workspace = true
hmac.workspace = true
omarchy-whatsapp-protocol = { version = "0.3.0", path = "../protocol" }
qrcode.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ureq.workspace = true
whatsapp-rust.workspace = true

[dev-dependencies]
flate2.workspace = true
rand.workspace = true
tempfile.workspace = true
